[alembic]
script_location = alembic
sqlalchemy.url = postgresql://fastapi:fastapi123@postgres:5432/fastapi_db

[post_write_hooks]
hooks = black
black.type = console_scripts
black.entrypoint = black
black.options = -l 79